# Generated by Django 3.2.3 on 2022-02-25 07:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='viewd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Checked', 'Checked'), ('Answered', 'Answered')], default='Sent', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Enter a brief content of the request', null=True),
        ),
    ]
