# Generated by Django 3.2.3 on 2022-02-25 08:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medcare', '0002_auto_20220225_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='viewd',
            new_name='viewed',
        ),
        migrations.AddField(
            model_name='request',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter a answer for this request', null=True),
        ),
    ]
