# Generated by Django 3.2.3 on 2022-02-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcare', '0003_auto_20220225_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
