from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='medcare/home.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('previous-ordered-product/', views.previously_order_product, name='previously-order-product'),
    path('products/', views.product_list, name='product-list'),
    path('product/<uuid:pk>/', views.product_detail, name='product-detail'),
    path('report/add/<uuid:pk>/', views.report_add, name='report_add'),
    path('news/<str:type>/', views.news_list, name='news-list'),
    path('news/detail/<uuid:pk>/', views.news_detail, name='news-detail'),
    path('requests/', views.request_get, name='request-list'),
    path('request/action/', views.request_action, name='request-action'),
    path('brands/', views.brand_list, name='brand-list'),
    path('brand/<uuid:pk>/', views.brand_get, name='brand-get'),
    path('categories/', views.category_list, name='category-list'),
    path('category/<uuid:pk>/', views.category_get, name='category-get'),
    path('cart/', views.cart, name='cart'),
    path('cart/add/<uuid:pk>/', views.cart_add, name='cart_add'),
    path('cart/increase/<uuid:pk>/', views.increase_product_in_cart, name='increase-product-in-cart'),
    path('cart/decrease/<uuid:pk>/', views.decrease_product_in_cart, name='decrease-product-in-cart'),
    path('cart/remove/<uuid:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/detail/<uuid:pk>', views.order_detail, name='order_detail'),
    path('order/remove/<uuid:pk>', views.order_remove, name='order_remove'),
    path('review/add/<uuid:pk>', views.review_add, name='review_add'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('coupon/', views.coupon_event, name='coupon'),
    path('generate/' , views.generate_data, name='generate'),
    path('search/' , views.search_product, name='search'),

    # Admin dashboard
    path('admin/dashboard', views.dashboard, name='dashboard'),
    path('admin/table', views.table, name='table'),
    path('admin/order/', views.order_manage, name='admin-order'), 
    path('admin/order/check/<uuid:pk>', views.check_order_status, name='admin-check-order-status'), 
    path('admin/order/<uuid:pk>', views.booking_detail, name='admin-booking-detail'),
    path('admin/product/', views.product_manage, name='admin-product'),
    path('admin/category/', views.category_manage, name='admin-category'),
    path('admin/category/<uuid:pk>', views.category_detail, name='admin-category-detail'),
    path('admin/brands/', views.brand_manage, name='admin-brand'),
    path('admin/users/', views.user_manage, name='admin-user'),
    path('admin/user/<uuid:pk>', views.user_detail, name='admin-user-detail'),
    path('admin/coupons/', views.coupon_manage, name='admin-coupon'),
    path('admin/requests/', views.request_manage, name='admin-request'),
    path('admin/reports/', views.report_manage, name='admin-report'),
    path('admin/news/', views.news_manage, name='admin-news'),
]
